### ISSUE TITLE
irmin-io polling continues after client kills cat command

### ISSUE THREAD

**Issue by philipdexter** [docker/datakit#178]
In running through the tutorial, I try the following command to watch a branch.

```
cat /db/branch/4.03/watch/tree.live
````

After an initial `irmin.watch [DEBUG] watch [1: 0k/0g]: id=0`,
the server starts start to echo
`irmin-io [DEBUG] polling /data/.git/refs/heads: no changes!` every second. When I `Ctrl-C` the client `cat` command the `irmin-io` logs continue, with no `irmin.watch` command signifying the watch has ended.

`Docker version 1.11.2, build b9f10c9`

I am running the datakit server as

```
docker run -it --net datakit-net --name datakit -v $(realpath .):/data docker/datakit
```

and the client as

```
docker run -it --privileged --net datakit-net docker/datakit:client
```

**Comment by talex5** [comment]
Ah, yes. There's a TODO about this here:

https://github.com/docker/datakit/blob/a38630ff56af4fcb0dbc3c48ca3e44c574f30bdb/src/ivfs/ivfs.ml#L519

There are several things that need fixing:

- 9p operations such as `read` should pass a cancel notifier to the handler. ocaml-9p added support for this a while back, but we don't plumb it through yet. Here's where it (`~cancel`) gets thrown away at the moment: https://github.com/docker/datakit/blob/a38630ff56af4fcb0dbc3c48ca3e44c574f30bdb/src/fs9p/fs9p.ml#L283
- We shouldn't have to keep monitoring/publishing events when the client isn't doing a read.
- We shouldn't be logging at debug level by default (#176).

It would probably be best to change (or add to) Irmin's watch API to support something like `Store.watch_head ~switch ~current`, which would produce a value later than `current` once one was available. Otherwise, we'll have to keep registering and removing watches all the time, which is clumsy.

/cc @samoht

**Comment by samoht** [comment]
An other thing we should fix is *not* do active polling but user FSEvents and Inotify on platforms which support it (e.g. not windows). I know that @dsheets had some plan to work on it at one point, but I guess if someone else wants to help, it's a relatively easy and self-contained task:

- need to implement the callback of [Irmin.Private.Watch.set_listen_dir_hook](https://mirage.github.io/irmin/Irmin.Private.Watch.html#VALset_listen_dir_hook) which takes a notification id (for debug purposes) and the path to watch, and a callback to apply any file which changes.
- on OSX, could use https://github.com/dsheets/ocaml-osx-fsevents
- on Linux, could use https://github.com/whitequark/ocaml-inotify

**Comment by samoht** [comment]
We are now using inotify and fsevents so this is less of an issue.
